# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ocr.grpc import ocr_service_pb2 as ocr_dot_grpc_dot_ocr__service__pb2


class OcrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunOcr = channel.unary_unary(
                '/ocr.OcrService/RunOcr',
                request_serializer=ocr_dot_grpc_dot_ocr__service__pb2.OcrRequest.SerializeToString,
                response_deserializer=ocr_dot_grpc_dot_ocr__service__pb2.OcrResponse.FromString,
                )


class OcrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunOcr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunOcr': grpc.unary_unary_rpc_method_handler(
                    servicer.RunOcr,
                    request_deserializer=ocr_dot_grpc_dot_ocr__service__pb2.OcrRequest.FromString,
                    response_serializer=ocr_dot_grpc_dot_ocr__service__pb2.OcrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OcrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OcrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunOcr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocr.OcrService/RunOcr',
            ocr_dot_grpc_dot_ocr__service__pb2.OcrRequest.SerializeToString,
            ocr_dot_grpc_dot_ocr__service__pb2.OcrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
