# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr/grpc/ocr_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aocr/grpc/ocr_service.proto\x12\x03ocr\"\x1c\n\nOcrRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\"g\n\x0bOcrResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08raw_text\x18\x03 \x01(\t\x12\x12\n\nlines_json\x18\x04 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x05 \x03(\t29\n\nOcrService\x12+\n\x06RunOcr\x12\x0f.ocr.OcrRequest\x1a\x10.ocr.OcrResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr.grpc.ocr_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OCRREQUEST']._serialized_start=35
  _globals['_OCRREQUEST']._serialized_end=63
  _globals['_OCRRESPONSE']._serialized_start=65
  _globals['_OCRRESPONSE']._serialized_end=168
  _globals['_OCRSERVICE']._serialized_start=170
  _globals['_OCRSERVICE']._serialized_end=227
# @@protoc_insertion_point(module_scope)
