# =========================
# Programming Languages
# =========================
java:
  - jdk
  - java8
  - java11
  - java17
  - jvm

kotlin:
  - kotin
  - kotln
  - kotlinlang

python:
  - py
  - python3
  - python2
  - py3
  - pyhton

javascript:
  - js
  - javascriptes
  - javasript
  - java-script

typescript:
  - ts
  - type-script
  - typescriptlang

# =========================
# Backend Frameworks
# =========================
spring:
  - springframework
  - spring-fw

spring boot:
  - springboot
  - spring-boot
  - spring_boot
  - spingboot
  - sprinboot

spring batch:
  - springbatch
  - spring-batch

spring security:
  - springsecurity
  - spring-security

nestjs:
  - nest
  - nest-js
  - nestjsframework

django:
  - django-rest
  - django-restframework
  - drf

fastapi:
  - fast-api
  - fast_api

express:
  - expressjs
  - express-js

# =========================
# Frontend Frameworks
# =========================
react:
  - reactjs
  - react-js
  - react.js

next.js:
  - nextjs
  - next-js
  - nextjsframework

vue:
  - vuejs
  - vue-js
  - vue.js

angular:
  - angularjs
  - angular-js

# =========================
# Databases
# =========================
mysql:
  - my-sql
  - mysql5
  - mysql8

postgresql:
  - postgres
  - postgresql-db
  - postgre
  - psql

mongodb:
  - mongo
  - mongo-db
  - mongodb-atlas

redis:
  - redis-cache
  - redisdb

elasticsearch:
  - elastic
  - elastic-search
  - es

opensearch:
  - open-search

# =========================
# Message / Streaming
# =========================
kafka:
  - apache-kafka
  - kafka-stream
  - kafka-streams

rabbitmq:
  - rabbit
  - rabbit-mq

sqs:
  - aws-sqs

pubsub:
  - pub-sub
  - google-pubsub

# =========================
# Infra / DevOps
# =========================
docker:
  - docker-compose
  - dockerfile
  - docker-container

kubernetes:
  - k8s
  - kube
  - kubernetes-engine

helm:
  - helmchart
  - helm-chart

terraform:
  - tf
  - terraform-io

ansible:
  - ansible-playbook

nginx:
  - nginx-server

apache:
  - apache-httpd

# =========================
# Cloud
# =========================
aws:
  - amazon-web-services
  - aws-cloud

ec2:
  - aws-ec2

s3:
  - aws-s3

rds:
  - aws-rds

lambda:
  - aws-lambda

gcp:
  - google-cloud
  - google-cloud-platform

azure:
  - microsoft-azure

# =========================
# API / Protocol
# =========================
rest:
  - restful
  - rest-api
  - restapi

graphql:
  - graph-ql
  - graphapi

grpc:
  - g-rpc
  - grpc-protocol

websocket:
  - ws
  - web-socket

# =========================
# Architecture / Concepts
# =========================
msa:
  - microservice
  - micro-service
  - microservices
  - micro-service-architecture

event-driven:
  - eventdriven
  - event-driven-architecture
  - eda

ddd:
  - domain-driven-design

tdd:
  - test-driven-development

ci/cd:
  - cicd
  - ci-cd
  - continuous-integration
  - continuous-delivery

# =========================
# Data / Analytics
# =========================
spark:
  - apache-spark

hadoop:
  - apache-hadoop

airflow:
  - apache-airflow

kafka streams:
  - kafka-streams-api

# =========================
# AI / ML (확장용)
# =========================
machine learning:
  - ml
  - machine-learning

deep learning:
  - dl
  - deep-learning

llm:
  - large-language-model
  - large-language-models

rag:
  - retrieval-augmented-generation
