spring:
  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.hirelog.com/login/oauth2/code/google
          kakao:
            redirect-uri: https://api.hirelog.com/login/oauth2/code/kakao
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    baseline-on-migrate: false # ⭐ 중요
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      enable-auto-commit: false
      group-id: hirelog-consumer-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: false

opensearch:
  host: ${OPENSEARCH_HOST}
  port: 9200
  scheme: http
  username: ''
  password: ''

hirelog:
  worker:
    job-summary:
      enabled: true

# application-prod.yml
app:
  storage:
    base-dir: /data/hirelog/storage

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: when_authorized

  metrics:
    tags:
      application: hirelog
      profile: prod

    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
