spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hirelog
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  kafka:
    admin:
      auto-create: false  # 운영환경에서는 false

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/google
          kakao:
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/kakao

  http:
    client:
      factory: http_components

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate     # ⭐ 핵심
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s

opensearch:
  host: localhost
  port: 9200
  scheme: https
  username: admin
  password: ${OPENSEARCH_PASSWORD}

hirelog:
  worker:
    job-summary:
      enabled: true

app:
  storage:
    base-dir: ${APP_STORAGE_BASE_DIR:/app/storage}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: hirelog
      profile: dev

    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
