ALTER TABLE board
    ADD COLUMN IF NOT EXISTS notice BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pinned_at TIMESTAMP NULL;

CREATE INDEX IF NOT EXISTS idx_board_pinned_created ON board (pinned, created_at DESC);
